<a href="https://colab.research.google.com/github/mkalokhina/practical_1_Kalokhina_Marharyta/blob/main/Practical_1_Kalokhina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) із послідовністю чисел,
  де кожне наступне число більше попереднього на 3, починаючи з 5,
  та виведіть його значення.)


In [2]:
import numpy as np
vector = np.arange(5, 5 + 3*10, 3)
print("Vector:", vector)

Vector: [ 5  8 11 14 17 20 23 26 29 32]


2. Створіть двовимірний масив (матрицю) розміром 3х3. заповніть його добутками квадратів кожного числа та його подвійного значення, починаючи з 1, та ниведіть його
значення.

In [3]:
matrix = np.array([[i**2 * (2*i) for i in range(1, 4)],
                    [i**2 * (2*i) for i in range(4, 7)],
                    [i**2 * (2*i) for i in range(7, 10)]])
print("Matrix 3x3:\n", matrix)

Matrix 3x3:
 [[   2   16   54]
 [ 128  250  432]
 [ 686 1024 1458]]


3. Створіть масив розміром 3х3, заповнить його випадковими дійсними числами в діапазоні від -5 до 5 та виведіть його значення

In [4]:
matrix = np.random.uniform(-5, 5, (3, 3))
print("Random Matrix 3x3:\n", matrix)

Random Matrix 3x3:
 [[-4.93620731 -1.20975946 -2.62399558]
 [ 1.75771846 -2.28012755 -2.51746835]
 [-4.4350464   2.28872531  2.70213819]]


4. Створіть масив розміром 4х4, заповніть його вицадковими дійсшими цислами д діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить середне значения елементів
кожного стовния матрик.

In [5]:
matrix = np.random.uniform(0, 1, (4, 4))
mean_vector = matrix.mean(axis=0)
print("Matrix 4x4:\n", matrix)
print("Mean Vector:", mean_vector)

Matrix 4x4:
 [[0.64448622 0.37566549 0.31767986 0.05564096]
 [0.86546699 0.81812476 0.61602689 0.17573477]
 [0.47843867 0.20745485 0.80369234 0.13882147]
 [0.28419207 0.37252523 0.55580906 0.45657084]]
Mean Vector: [0.56814599 0.44344258 0.57330203 0.20669201]


5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними числами від -2,5 до 2,5 та виконайте на них поелементі операції додавання. віднімання та множення.

In [6]:
vector_1 = np.random.uniform(-2.5, 2.5, 7)
vector_2 = np.random.uniform(-2.5, 2.5, 7)

add_result = vector_1 + vector_2
sub_result = vector_1 - vector_2
mul_result = vector_1 * vector_2

print("Addition Result:", add_result)
print("Subtraction Result:", sub_result)
print("Multiplication Result:", mul_result)

Addition Result: [ 0.93836867  0.80358964  2.56913514  0.45253884 -0.87179744  2.39622866
 -0.4452243 ]
Subtraction Result: [ 1.41410716 -1.52351799  0.10180462 -2.11091671 -3.91539996 -1.30298638
  0.5257285 ]
Multiplication Result: [-0.27979083 -0.41883769  1.6475228  -1.06279448 -3.64258152  1.01103457
 -0.01954145]


6. Створіть дві матриці 3к3, заповнить їх довльними шлими числами ви 1 до 50 та знайдіть їх добуток.

In [7]:
matrix_6_1 = np.random.randint(1, 51, (3, 3))
matrix_6_2 = np.random.randint(1, 51, (3, 3))
matrix_6_product = np.dot(matrix_6_1, matrix_6_2)

print("Matrix 6_1:\n", matrix_6_1)
print("Matrix 6_2:\n", matrix_6_2)
print("Matrix Product:\n", matrix_6_product)

Matrix 6_1:
 [[15  3 15]
 [ 9 49 49]
 [25 36  8]]
Matrix 6_2:
 [[ 4 33 28]
 [31 12 14]
 [43  1  4]]
Matrix Product:
 [[ 798  546  522]
 [3662  934 1134]
 [1560 1265 1236]]


7. Створіть дві матриці розміром 4×2 та 2х2. заповніть іх винадковими цілими числами в діапазоні від 1 до 6 та перемножте їх мі собою.

In [8]:
matrix_1 = np.random.randint(1, 7, (4, 2))
matrix_2 = np.random.randint(1, 7, (2, 2))
matrix_product = np.dot(matrix_1, matrix_2)

print("\nMatrix 1:\n", matrix_1)
print("Matrix 2:\n", matrix_2)
print("Matrix Product:\n", matrix_product)



Matrix 1:
 [[4 4]
 [2 2]
 [6 6]
 [3 1]]
Matrix 2:
 [[5 4]
 [2 3]]
Matrix Product:
 [[28 28]
 [14 14]
 [42 42]
 [17 15]]


8. Створіть матрицю розміром 2х2, заповнить ті випадковими шлими числами в діапазоні від 1 до 12 та знайдіть ії оберисну матришю.

In [9]:
matrix = np.random.randint(1, 13, (2, 2))
matrix_inverse = np.linalg.inv(matrix)
print("\nMatrix:\n", matrix)
print("Inverse Matrix:\n", matrix_inverse)


Matrix:
 [[ 8  8]
 [ 4 12]]
Inverse Matrix:
 [[ 0.1875 -0.125 ]
 [-0.0625  0.125 ]]


9. Створить матрицю розміром 3х3, заповніть 17 випадковими телими числами в дапазоні вд. 0 до 1 та трансповуйте ті.

In [10]:
matrix = np.random.uniform(0, 1, (3, 3))
matrix_transposed = matrix.T

print("\nMatrix:\n", matrix)
print("Transposed Matrix:\n", matrix_transposed)


Matrix:
 [[0.57925579 0.48925096 0.29059033]
 [0.01102539 0.62625517 0.58971677]
 [0.17054306 0.80708883 0.19402045]]
Transposed Matrix:
 [[0.57925579 0.01102539 0.17054306]
 [0.48925096 0.62625517 0.80708883]
 [0.29059033 0.58971677 0.19402045]]


10. Створіть матришю розміром 34 та вектор розміром 4х1, заповніть матрицю випадковими цілими числами в діапазоні від -5 до 5, а вектор - випадковими цілими числами в діапазоні від І до 10, і знайдіть добуток матриці на вектор.

In [11]:
matrix = np.random.randint(-5, 6, (4, 4))
vector = np.random.randint(1, 11, (4, 1))
matrix_product = np.dot(matrix, vector)

print("\nMatrix:\n", matrix)
print("Vector:\n", vector)
print("Matrix-Vector Product:\n", matrix_product)


Matrix:
 [[ 4 -3  5  3]
 [ 0 -1 -4  3]
 [-1 -4 -5  1]
 [-4  2  3 -2]]
Vector:
 [[9]
 [7]
 [7]
 [1]]
Matrix-Vector Product:
 [[ 53]
 [-32]
 [-71]
 [ -3]]


11. Створіть матришю розміром 2х3 та вектор розміром 3х1, заповніть матрицю вишанковими дійспими числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від І до 10, і знайдіть добуток матриці на вектор.

In [12]:
matrix = np.random.uniform(0, 1, (2, 3))
vector = np.random.randint(1, 11, (3, 1))
matrix_product = np.dot(matrix, vector)

print("\nMatrix:\n", matrix)
print("Vector:\n", vector)
print("Matrix-Vector Product:\n", matrix_product)


Matrix:
 [[0.85164061 0.01403608 0.57019586]
 [0.55680396 0.24022438 0.68701483]]
Vector:
 [[2]
 [1]
 [1]]
Matrix-Vector Product:
 [[2.28751315]
 [2.04084715]]


12. Створіть дві матриці розміром 8х8, заповніть їх випадковими цілими чиелами в діапазоші від 1 до 10 та знайціть іхо суму.

In [13]:
matrix_1 = np.random.randint(1, 11, (8, 8))
matrix_2 = np.random.randint(1, 11, (8, 8))
matrix_sum = matrix_1 + matrix_2

print("Matrix 1:\n", matrix_1)
print("Matrix 2:\n", matrix_2)
print("Matrix Sum:\n", matrix_sum)

Matrix 1:
 [[ 1  2  9  8 10  5  5  9]
 [ 4  1  1  9  7  4  8 10]
 [ 1  1  5  4  5  3 10  7]
 [ 2  5  7  5  7  5  4  5]
 [ 4  3  2  6  5  3  9  2]
 [10 10  2  3  9 10  3  6]
 [ 8  4  1  8  7 10  7  7]
 [ 1  4  5  3  8  3  3  5]]
Matrix 2:
 [[ 7  4  7  9 10  4  5  1]
 [ 8 10  1  5  6  8  2  8]
 [ 6  9  6  1  2  6  8  4]
 [ 1  2  4  8  7  8  1  7]
 [ 6  2  6  5  4 10  7  5]
 [ 2  2  4  2  9  7  1  7]
 [ 4  1  1  1 10  9  2  2]
 [ 3  9  4  9  2  4  2  4]]
Matrix Sum:
 [[ 8  6 16 17 20  9 10 10]
 [12 11  2 14 13 12 10 18]
 [ 7 10 11  5  7  9 18 11]
 [ 3  7 11 13 14 13  5 12]
 [10  5  8 11  9 13 16  7]
 [12 12  6  5 18 17  4 13]
 [12  5  2  9 17 19  9  9]
 [ 4 13  9 12 10  7  5  9]]


13. Створіть дві матриці розміром 8х8, заповніть їх випадковими дійсними числами в діапазоні від - 1 до 1 та знайдіть різницю їх слементів.

In [15]:
matrix_1 = np.random.uniform(-1, 1, (8, 8))
matrix_2 = np.random.uniform(-1, 1, (8, 8))
matrix_diff = matrix_1 - matrix_2

print("Matrix 1:\n", matrix_1)
print("Matrix 2:\n", matrix_2)
print("Matrix Difference:\n", matrix_diff)

Matrix 1:
 [[-0.43382537  0.19549072 -0.78350846 -0.19900598 -0.48547573 -0.08720522
   0.82092528  0.65160777]
 [-0.35241051 -0.24870584 -0.49182201  0.65171509  0.58641951 -0.25698164
  -0.1357755  -0.01666104]
 [-0.35404758  0.29102195 -0.76087757 -0.54093716 -0.28526674 -0.86479133
   0.5433356  -0.99139761]
 [-0.01867216 -0.85094256 -0.10900043  0.1081812  -0.14574534  0.81427962
  -0.61432687  0.28402697]
 [ 0.95153871 -0.89988332 -0.73785339 -0.06198065  0.31607545 -0.40265282
   0.47831009  0.85856688]
 [ 0.78064036 -0.79201069 -0.24165716 -0.78659741 -0.41768786 -0.45973124
  -0.56538825 -0.71503397]
 [-0.85474122  0.84736009 -0.8920523  -0.48435872  0.17857483 -0.407788
   0.98491894 -0.98006146]
 [ 0.6589158  -0.17100211 -0.15704083 -0.38092167  0.33264632 -0.51546064
  -0.54974707  0.45090948]]
Matrix 2:
 [[-0.24863421  0.43401075  0.8133156   0.5700985  -0.12326843 -0.93331958
  -0.40839177 -0.69570566]
 [-0.02139428  0.04682583 -0.25155933 -0.41905767 -0.70153729 -0.18293

14. Створіть матрицю розміром 5х5, заповніть п випадковими йоними числами в діапазоні віл 0 ло 1 та знайдіть середне арифметичие значення елементів матриці.

In [16]:
matrix = np.random.uniform(0, 1, (5, 5))
matrix_mean = matrix.mean()
print("Matrix:\n", matrix)
print("Mean Value:", matrix_mean)

Matrix:
 [[0.12626525 0.21298703 0.72473915 0.63099289 0.70529   ]
 [0.63082963 0.64503523 0.11862194 0.58026443 0.46548102]
 [0.74277029 0.77557459 0.71356212 0.54548765 0.44549687]
 [0.00328866 0.65050149 0.06190047 0.08145493 0.56125654]
 [0.63751235 0.90917885 0.81790529 0.18710622 0.8346357 ]]
Mean Value: 0.512325542942287


15. Створіть матрицю розміром 9×9, заповніть її випадковими дайсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовичик, що містить найбільше за модудем значения елементу у кожному рядку магриці.

In [17]:
matrix = np.random.uniform(-0.5, 0.5, (9, 9))
max_abs_vector = np.max(np.abs(matrix), axis=1)

print("Matrix:\n", matrix)
print("Max Absolute Value Vector:\n", max_abs_vector)

Matrix:
 [[ 0.22994312 -0.12701592 -0.20896476 -0.11346567 -0.3496872   0.11069309
   0.01392498 -0.33919922  0.17462326]
 [ 0.26602434  0.34407898  0.45507445  0.25018176 -0.36002838 -0.26993047
  -0.26912526  0.46763626 -0.25988079]
 [ 0.1110854   0.05382739 -0.15945587  0.3545335   0.46533578 -0.46371218
   0.3802034   0.16368472 -0.49601861]
 [-0.14363505  0.08493219 -0.47134216  0.40484063  0.09819881 -0.43456339
  -0.05211423  0.26533157  0.26739507]
 [-0.27601568  0.35385123 -0.26093191 -0.02588694 -0.26338062 -0.00622184
  -0.41829525  0.04438072  0.26256945]
 [-0.41154499 -0.41232189  0.05970595  0.45688379  0.36177056  0.49398805
  -0.21961029  0.24048065  0.01724625]
 [ 0.2025734   0.24352259  0.18203551 -0.0145797  -0.04005629 -0.11610164
   0.34408786 -0.18074984  0.42599275]
 [ 0.47314616  0.35250307  0.31621479 -0.31469813  0.21995547  0.46632121
   0.26097139  0.49344814  0.18223171]
 [-0.35898064  0.30559031 -0.01907643  0.04628461 -0.28269045 -0.24271641
  -0.452943  

Виконані завдання продемонстрували, як багатогранні можливості бібліотеки NumPy дозволяють ефективно вирішувати різні математичні
й аналітичні задачі. Операції з матрицями й векторами, випадкові значення та обчислення статистичних характеристик дали змогу на практиці відчути,
наскільки гнучкою і потужною є ця бібліотека для моделювання складних систем. Це підкреслює важливість вміння працювати з масивами даних,
адже в реальних задачах часто виникає необхідність обробки великих обсягів інформації через подібні математичні операції.
